### ISSUE TITLE
Options on right in the Add Meet page are not greyed out

### ISSUE THREAD

**Issue by mckouba** [mckouba/Northern-Ski-League-With-GUI#3]
Need to make sure the combo boxes and text boxes are not enabled until after a season is selected on the Add Meet page.  This applies to when the Add and Edit option is selected.

**Comment by RyanMeeker** [comment]
I need to finished the if() statement so that when a season is selected it turns all of hidden names to true but I'm going to watch WW so if I finish it it'll be late tonight/tomorrow or if you want to you can do it. I pushed my commits to my branch.

**Comment by mckouba** [comment]
There seems to be a bug where when things do not have their IsEnabled flag set correctly everytime, so this will not get fixed anytime soon.  Another fix for this will be issue #6.

**Comment by mckouba** [comment]
Something that might help is to set the IsEnabled flag like this: `IsEnabled = true` instead of `IsEnabled = "true"`

**Comment by mckouba** [comment]
Fixed with merge #23
